### ISSUE TITLE
ViCi Web3Conect

### ISSUE THREAD

**Issue by IllIYAAAllI** [taikai/dappkit#41]
https://github.com/taikai/dappkit/blob/72463a5266fe15dd75e5b78e4af78dcd4d635fb5/src/base/web3-connection.ts#L11

**Comment by moshmage** [comment]
use `Account`, https://github.com/taikai/dappkit/blob/72463a5266fe15dd75e5b78e4af78dcd4d635fb5/src/base/web3-connection.ts#L24
