### ISSUE TITLE
ERC721Marketplace | reentrance

### ISSUE THREAD

**Issue by lucasarchangelo** [taikai/dappkit#64]
**Describe the bug**

I think I found a vulnerability on ERC721Marketplace.sol
I think reentrance could be possible if you use isNativeTransaction to buy ERC721, the contract requires that the Token wasn't sold yet, but it only modifies its state after all things are done.
If you create a reentrance contract, it could call multiple times and send native tokens to nft owner.

**Reproduction**

**Logs, screenshots**

**versions, packages, etc**

**Additional context**

**Comment by moshmage** [comment]
Closing as address on https://github.com/taikai/dappkit/pull/73
